import React from 'react';
import { Tag, Plus, X } from 'lucide-react';

interface TagItem {
  name: string;
  category: string;
  confidence: number;
}

interface TagsData {
  autoGenerated: TagItem[];
  userDefined: TagItem[];
}

interface TagsPanelProps {
  tagsData: TagsData;
  loading?: boolean;
}

const TagsPanel: React.FC<TagsPanelProps> = ({ tagsData, loading = false }) => {
  if (loading) {
    return (
      <div className="bg-white rounded-lg shadow p-6">
        <h3 className="text-lg font-medium mb-4">Tags</h3>
        <div className="animate-pulse space-y-3">
          <div className="h-4 bg-gray-200 rounded w-3/4"></div>
          <div className="h-4 bg-gray-200 rounded w-1/2"></div>
          <div className="h-4 bg-gray-200 rounded w-2/3"></div>
        </div>
      </div>
    );
  }

  const getCategoryColor = (category: string) => {
    switch (category.toLowerCase()) {
      case 'topic':
        return 'bg-blue-100 text-blue-800';
      case 'sentiment':
        return 'bg-green-100 text-green-800';
      case 'language':
        return 'bg-purple-100 text-purple-800';
      case 'content-type':
        return 'bg-orange-100 text-orange-800';
      default:
        return 'bg-gray-100 text-gray-800';
    }
  };

  const renderTags = (tags: TagItem[], title: string) => {
    if (!tags || tags.length === 0) return null;

    return (
      <div>
        <h4 className="text-sm font-medium mb-3">{title}</h4>
        <div className="flex flex-wrap gap-2">
          {tags.map((tag, index) => (
            <div 
              key={index}
              className="flex items-center space-x-1 group"
            >
              <span className={`inline-flex items-center px-2 py-1 rounded text-xs font-medium ${getCategoryColor(tag.category)}`}>
                <Tag className="h-3 w-3 mr-1" />
                {tag.name}
              </span>
              <span className="text-xs text-gray-500">
                {tag.confidence.toFixed(2)}
              </span>
            </div>
          ))}
        </div>
      </div>
    );
  };

  return (
    <div className="bg-white rounded-lg shadow p-6">
      <div className="flex items-center justify-between mb-4">
        <h3 className="text-lg font-medium">Tags</h3>
        <button className="inline-flex items-center px-2 py-1 border border-gray-300 shadow-sm text-xs leading-4 font-medium rounded-md text-gray-700 hover:bg-gray-50">
          <Plus className="h-3 w-3 mr-1" />
          Add Tag
        </button>
      </div>
      
      <div className="space-y-4">
        {/* Auto-generated Tags */}
        {renderTags(tagsData.autoGenerated, "Auto-generated Tags")}
        
        {/* User-defined Tags */}
        {renderTags(tagsData.userDefined, "User-defined Tags")}
        
        {/* Empty State */}
        {(!tagsData.autoGenerated || tagsData.autoGenerated.length === 0) && 
         (!tagsData.userDefined || tagsData.userDefined.length === 0) && (
          <div className="text-center py-6">
            <Tag className="mx-auto h-8 w-8 text-gray-400" />
            <h3 className="mt-2 text-sm font-medium text-gray-900">No tags available</h3>
            <p className="mt-1 text-sm text-gray-500">
              Tags will appear here when content is analyzed.
            </p>
          </div>
        )}
      </div>
    </div>
  );
};

export default TagsPanel;